### ISSUE TITLE
Using the module it doens't get passed the Login Screen (OSOE-902)

### ISSUE THREAD

**Issue by beerpal243** [Lombiq/Orchard-Walkthroughs#21]
When running the Walkthrough, it gets to the login page, but then it doesn't enter the credentials to get to the admin portal.  It appears the JavaScript is not finding the fields to fill in correctly 

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-902)

**Comment by Piedone** [comment]
Please be more specific, since this is covered by a UI test and it's passing. Which version are you using with which OC version? Note that v1.0.1 is only compatible with OC 1.8.x; it's only the latest source in the `task/system-text-json-migration` branch that work with the recent OC previews.

**Comment by Piedone** [comment]
Closing as no reply from author.

**Comment by beerpal243** [comment]
Yeah, I was using 2.0.  So, that makes sense.

**Comment by Piedone** [comment]
The v2.0.0 version of the module we released last week is compatible with OC v2.0.0 BTW.
